# Generated by Django 2.2.6 on 2019-10-24 05:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.SmallIntegerField(max_length=20)),
                ('descripcion', models.SmallIntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.SmallIntegerField(max_length=20)),
                ('descripcion', models.SmallIntegerField(max_length=20)),
            ],
            options={
                'verbose_name': 'Nacionalidades',
                'verbose_name_plural': 'Nacionalidad',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.SmallIntegerField(max_length=20)),
                ('descripcion', models.SmallIntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID Unica', primary_key=True, serialize=False)),
                ('nombre', models.SmallIntegerField(blank=True, help_text='Ingrese Nombre cliente', max_length=200)),
                ('apellido', models.SmallIntegerField(blank=True, help_text='Ingrese Apellido cliente', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Ingrese Correo cliente', max_length=50, verbose_name='Email')),
                ('inicio', models.DateField(help_text='Ingrese Fecha Inicio viaje')),
                ('fin', models.DateField(help_text='Ingrese Fecha Termino viaje')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Destino')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Nacionalidad')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Transporte')),
            ],
            options={
                'verbose_name': 'Clientes',
                'verbose_name_plural': 'Cliente',
            },
        ),
    ]
