# Generated by Django 2.2.6 on 2019-10-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.SmallIntegerField(blank=True, help_text='Ingrese Apellido cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, help_text='Ingrese Nombre cliente', max_length=200),
        ),
        migrations.AlterField(
            model_name='destino',
            name='descripcion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='destino',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nacionalidad',
            name='descripcion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nacionalidad',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='descripcion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
