# Generated by Django 2.2.6 on 2019-10-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191026_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, help_text='Ingrese Apellido cliente', max_length=200),
        ),
    ]
